version: "3.9"

services:
  class_build:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./pages:/class_build/pages
      - ./src:/class_build/src
    ports:
      - 3000:3000
